name: express-mysql-js-server CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Node.js 버전을 지정(Node.js 18.x). 필요에 따라 버전 변경 가능
          cache: 'yarn'       # Yarn 캐시 활성화

      # Yarn 설치
      - name: Install Yarn
        run: npm install -g yarn

      # 의존성 설치
      - name: Install dependencies
        run: yarn install

      # 빌드 단계
      - name: Build
        run: yarn build

      # 로컬 서버 시작
      - name: Start API Server
        run: node server.js & echo $! > PIDFILE

      # 서버 시작 후 5초간 작업 중지
      - name: Delay for server startup
        run: sleep 5

      # API 테스트 단계
      - name: API Tests
        run: |
          curl -s http://localhost:5000/api/get/books
          curl -s http://localhost:5000/api/get/auth/login
          curl -s http://localhost:5000/api/get/admin/user-info
          curl -s http://localhost:5000/api/get/blog/posts

      # 프로세스 종료
      - name: Stop API Server
        run: |
          kill $(cat PIDFILE)
          rm PIDFILE